### ISSUE TITLE
crash when there's error connecting to server

### ISSUE THREAD

**Issue by brucexia0** [nkzawa/engine.io-client.java#16]
Looks like a invalid delay value passed to reconnect. I'm running this on latest version   
  compile 'com.github.nkzawa:socket.io-client:0.4.1'

```
03-30 20:46:40.113: E/AndroidRuntime(10931): FATAL EXCEPTION: EventThread
03-30 20:46:40.113: E/AndroidRuntime(10931): Process: agilie.fandine.employee, PID: 10931
03-30 20:46:40.113: E/AndroidRuntime(10931): java.lang.IllegalArgumentException: delay < 0: -432345566375051264
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at java.util.Timer.schedule(Timer.java:457)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.socketio.client.Manager.reconnect(Manager.java:497)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.socketio.client.Manager.access$2000(Manager.java:20)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.socketio.client.Manager$8$1$1.call(Manager.java:519)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.socketio.client.Manager$1$3.call(Manager.java:282)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.Socket.onError(Socket.java:754)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.Socket$4.call(Socket.java:293)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.Transport.onError(Transport.java:63)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:19)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:126)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-30 20:46:40.113: E/AndroidRuntime(10931): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by nkzawa** [comment]
This is already fixed. Please bump to v0.4.2.
